{{- if .Values.slcs.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ template "fullname" . }}-postgres-slcs"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: slcs
    slcs-role: database
spec:
  accessModes:
    - ReadWriteOnce
{{- if .Values.slcs.postgres.persistence.storageClass }}
  storageClassName: "{{ .Values.slcs.postgres.persistence.storageClass }}"
{{- end }}
  resources:
    requests:
      storage: {{ .Values.slcs.postgres.persistence.size }}
{{- if .Values.slcs.postgres.persistence.selector }}
  selector:
{{ toYaml .Values.slcs.postgres.persistence.selector | indent 4 }}
{{- end }}
{{- end }}
