apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-slcs"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: slcs
    slcs-role: frontend
spec:
  ports:
    - name: http
      port: 8000
  selector:
    release: {{ .Release.Name }}
    component: slcs
    slcs-role: frontend
