apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-postgres-auth"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: auth
    auth-role: database
spec:
  ports:
    - name: postgres
      port: 5432
  selector:
    release: {{ .Release.Name }}
    component: auth
    auth-role: database
