{{- if .Values.solr.master.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ template "fullname" . }}-solr-master"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: solr
    solr-role: master
spec:
  accessModes:
    - ReadWriteOnce
{{- if .Values.solr.master.persistence.storageClass }}
  storageClassName: "{{ .Values.solr.master.persistence.storageClass }}"
{{- end }}
  resources:
    requests:
      storage: {{ .Values.solr.master.persistence.size }}
{{- if .Values.solr.master.persistence.selector }}
  selector:
{{ toYaml .Values.solr.master.persistence.selector | indent 4 }}
{{- end }}
{{- end }}
