apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-solr-slave"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: solr
    solr-role: slave
spec:
  ports:
    - name: solr
      port: 8983
  selector:
    release: {{ .Release.Name }}
    component: solr
    solr-role: slave
