{{- $accessLogSidecar := .Values.data.accessLogSidecar -}}
{{- $statsPipeline := $accessLogSidecar.statsPipeline -}}
{{- if (and .Values.data.enabled $accessLogSidecar.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "esgf.component.fullname" (list . "logstash-certs") }}
  labels: {{ include "esgf.component.labels" (list . "logstash" dict) | nindent 4 }}
data:
{{- if $statsPipeline.enabled }}
  lumberjack.cert: {{ $statsPipeline.certificate | b64enc | quote }}
{{- end }}
{{- end }}
