version: "3.0"

volumes: 
  slcs_static_web: 

networks: 
  dbnetwork: 
    external: 
      name: esgfdocker_dbnetwork

services: 
  slcs: 
    command: ["-sn", "slcs-server", "-ds", "rootAdmin", "-sdn", "slcs", "-sdh", "slcs-postgres", "-sdu", "dbsuper", "-udn", "esgcet", "-udh", "postgres", "-udu", "dbsuper", "--static-url", "https://$ESGF_HOSTNAME/slcs/"]
    container_name: slcs-server
    depends_on: 
      - slcs-postgres
      - slcs-nginx
    expose: 
      - "5000"
    image: esgfhub/slcs-server
    networks: 
      - default
      - dbnetwork
    ports: 
      - "5000:5000"
    volumes: 
      - "slcs_static_web:/var/www/static"
      - "$ESGF_CONFIG/slcs/conf/db/:/usr/local/esgf-slcs-server/conf/db"
      - "$ESGF_CONFIG/slcs/conf/ca/:/usr/local/esgf-slcs-server/conf/ca"
  
  slcs-nginx: 
    container_name: slcs-nginx
    expose: 
      - "443"
      - "80"
    image: nginx
    networks: 
      - default
      - dbnetwork
    volumes: 
      - "slcs_static_web:/usr/share/nginx/html"
      - "$ESGF_CONFIG/slcs/conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "$ESGF_CONFIG/slcs/conf/nginx/nginx-start.sh:/usr/bin/start-nginx.sh"
  
  slcs-postgres: 
    container_name: slcs-postgres
    environment: 
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_USER=dbsuper
      - POSTGRES_DB=slcs
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    expose: 
      - "5432"
    image: postgres
    networks: 
      - default
      - dbnetwork
