---

###
# Default values used for all images
# Each of these values can be overidden on a per-image basis if required
###

# The image prefix to use
# If using a private registry, change this, e.g. registry.ceda.ac.uk/esgfdeploy
image_prefix: esgfdeploy
# The image tag to use
image_tag: latest
# Indicates whether images should be pulled every time the playbook runs
# When using mutable tags, like latest or branch names, this should be true
# When using immutable tags, like commit shas or release tags, this can be false
image_pull: true

###
# Auth configuration
###
# Indicates if the auth service should be deployed or not
auth_enabled: false

# Default rego template (override this to use your own)
auth_policy_template: policy.rego.j2
auth_policy_restricted_paths: []

# Logging level for the OPA server
opa_log_level: debug

# Settings for the opa image
opa_image_prefix: "{{ image_prefix }}"
opa_image_tag: "{{ image_tag }}"
opa_image_pull: "{{ image_pull }}"
opa_image_repository: opa

# Settings for the auth-service image
auth_image_prefix: "{{ image_prefix }}"
auth_image_tag: "{{ image_tag }}"
auth_image_pull: "{{ image_pull }}"
auth_image_repository: auth-service
