#####
# Docker Compose file to build ESGF containers
#####

version: '3.4'


services:
  esgf-configure:
    image: "${ESGF_HUB}/${ESGF_PREFIX}configure:${ESGF_VERSION}"
    build: ./configure
    entrypoint: ["true"]

  esgf-postgres:
    image: "${ESGF_HUB}/${ESGF_PREFIX}postgres:${ESGF_VERSION}"
    build: ./postgres
    entrypoint: ["true"]

  esgf-solr:
    image: "${ESGF_HUB}/${ESGF_PREFIX}solr:${ESGF_VERSION}"
    build: ./solr
    entrypoint: ["true"]

  esgf-tomcat:
    image: "${ESGF_HUB}/${ESGF_PREFIX}tomcat:${ESGF_VERSION}"
    build: ./tomcat
    entrypoint: ["true"]

  esgf-django:
    image: "${ESGF_HUB}/${ESGF_PREFIX}django:${ESGF_VERSION}"
    build: ./django
    entrypoint: ["true"]

  esgf-setup:
    image: "${ESGF_HUB}/${ESGF_PREFIX}setup:${ESGF_VERSION}"
    build:
      context: ./setup
      args:
        ESGF_HUB: $ESGF_HUB
        ESGF_PREFIX: $ESGF_PREFIX
        ESGF_VERSION: $ESGF_VERSION
    entrypoint: ["true"]
    depends_on:
      - esgf-configure

  esgf-publisher:
    image: "${ESGF_HUB}/${ESGF_PREFIX}publisher:${ESGF_VERSION}"
    build:
      context: ./publisher
      args:
        ESGF_HUB: $ESGF_HUB
        ESGF_PREFIX: $ESGF_PREFIX
        ESGF_VERSION: $ESGF_VERSION
    entrypoint: ["true"]
    depends_on:
      - esgf-configure

  esgf-proxy:
    image: "${ESGF_HUB}/${ESGF_PREFIX}proxy:${ESGF_VERSION}"
    build:
      context: ./proxy
      args:
        ESGF_HUB: $ESGF_HUB
        ESGF_PREFIX: $ESGF_PREFIX
        ESGF_VERSION: $ESGF_VERSION
    entrypoint: ["true"]
    depends_on:
      - esgf-configure

  esgf-postgres-security:
    image: "${ESGF_HUB}/${ESGF_PREFIX}postgres-security:${ESGF_VERSION}"
    build:
      context: ./postgres-security
      args:
        ESGF_HUB: $ESGF_HUB
        ESGF_PREFIX: $ESGF_PREFIX
        ESGF_VERSION: $ESGF_VERSION
    entrypoint: ["true"]
    depends_on:
      - esgf-postgres

  esgf-orp:
    image: "${ESGF_HUB}/${ESGF_PREFIX}orp:${ESGF_VERSION}"
    build:
      context: ./orp
      args:
        ESGF_HUB: $ESGF_HUB
        ESGF_PREFIX: $ESGF_PREFIX
        ESGF_VERSION: $ESGF_VERSION
    entrypoint: ["true"]
    depends_on:
      - esgf-configure
      - esgf-tomcat

  esgf-index-node:
    image: "${ESGF_HUB}/${ESGF_PREFIX}index-node:${ESGF_VERSION}"
    build:
      context: ./index-node
      args:
        ESGF_HUB: $ESGF_HUB
        ESGF_PREFIX: $ESGF_PREFIX
        ESGF_VERSION: $ESGF_VERSION
    entrypoint: ["true"]
    depends_on:
      - esgf-configure
      - esgf-tomcat

  esgf-idp-node:
    image: "${ESGF_HUB}/${ESGF_PREFIX}idp-node:${ESGF_VERSION}"
    build:
      context: ./idp-node
      args:
        ESGF_HUB: $ESGF_HUB
        ESGF_PREFIX: $ESGF_PREFIX
        ESGF_VERSION: $ESGF_VERSION
    entrypoint: ["true"]
    depends_on:
      - esgf-configure
      - esgf-tomcat

  esgf-tds:
    image: "${ESGF_HUB}/${ESGF_PREFIX}tds:${ESGF_VERSION}"
    build:
      context: ./tds
      args:
        ESGF_HUB: $ESGF_HUB
        ESGF_PREFIX: $ESGF_PREFIX
        ESGF_VERSION: $ESGF_VERSION
    entrypoint: ["true"]
    depends_on:
      - esgf-configure
      - esgf-tomcat

  esgf-cog:
    image: "${ESGF_HUB}/${ESGF_PREFIX}cog:${ESGF_VERSION}"
    build:
      context: ./cog
      args:
        ESGF_HUB: $ESGF_HUB
        ESGF_PREFIX: $ESGF_PREFIX
        ESGF_VERSION: $ESGF_VERSION
    entrypoint: ["true"]
    depends_on:
      - esgf-configure
      - esgf-django

  esgf-auth:
    image: "${ESGF_HUB}/${ESGF_PREFIX}auth:${ESGF_VERSION}"
    build:
      context: ./auth
      args:
        ESGF_HUB: $ESGF_HUB
        ESGF_PREFIX: $ESGF_PREFIX
        ESGF_VERSION: $ESGF_VERSION
    entrypoint: ["true"]
    depends_on:
      - esgf-configure
      - esgf-django

  esgf-slcs:
    image: "${ESGF_HUB}/${ESGF_PREFIX}slcs:${ESGF_VERSION}"
    build:
      context: ./slcs
      args:
        ESGF_HUB: $ESGF_HUB
        ESGF_PREFIX: $ESGF_PREFIX
        ESGF_VERSION: $ESGF_VERSION
    entrypoint: ["true"]
    depends_on:
      - esgf-django
