{{- if .Values.auth.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "esgf.component.fullname" (list . "ingressAuth") }}
  labels: {{ include "esgf.component.labels" (list . "ingressAuth" .Values.ingress.labels) | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{ include "esgf.ingress.tls" . | indent 2 }}
  rules:
    - host: {{ .Values.hostname | quote }}
      http:
        paths:
          - path: /verify
            backend:
              serviceName: {{ include "esgf.component.fullname" (list . "auth") }}
              servicePort: 8080
          - path: /login
            backend:
              serviceName: {{ include "esgf.component.fullname" (list . "auth") }}
              servicePort: 8080
          {{- if .Values.opa.enabled }}
          - path: /v1/data
            backend:
              serviceName: {{ include "esgf.component.fullname" (list . "opa") }}
              servicePort: 8181
          {{- end }}
{{- end }}
