apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "esgf.component.fullname" (list . "ingress") }}
  labels: {{ include "esgf.component.labels" (list . "ingress" .Values.ingress.labels) | nindent 4 }}
  {{- if .Values.auth.enabled }}
  annotations:
    # Auth service configuration
    nginx.ingress.kubernetes.io/auth-url: "http://esgf-auth.default.svc.cluster.local:8080/verify/"
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Original-URI $request_uri;
    nginx.ingress.kubernetes.io/auth-signin: "https://$host:8443/login/"
    {{- with .Values.ingress.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.hostname | quote }}
      {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName }}
      {{- else }}
      secretName: {{ include "esgf.component.fullname" (list . "hostcert") }}
      {{- end }}
  rules:
    - host: {{ .Values.hostname | quote }}
      http:
        paths:
          {{- if .Values.data.enabled }}
          {{- if .Values.data.thredds.enabled }}
          - path: /thredds
            backend:
              serviceName: {{ include "esgf.component.fullname" (list . "thredds") }}
              servicePort: 8080
          {{- end }}
          {{- if .Values.data.fileServer.enabled }}
          - path: /thredds/fileServer
            backend:
              serviceName: {{ include "esgf.component.fullname" (list . "fileServer") }}
              servicePort: 8080
          {{- end }}
          {{- end }}
          {{- if .Values.index.enabled }}
          {{- if .Values.index.solr.enabled }}
          # We only want to permit access to the replication handler for each core from outside
          # However wildcard paths are not supported on all ingress controllers
          # So we make a path definition for each core
          - path: /solr/aggregations/replication
            backend: &solr
              # We point to the Solr slave
              serviceName: {{ include "esgf.component.fullname" (list . "solr" "slave") }}
              servicePort: 8983
          - path: /solr/datasets/replication
            backend: *solr
          - path: /solr/files/replication
            backend: *solr
          {{- end }}
          {{- if .Values.index.search.enabled }}
          - path: /esg-search
            backend:
              serviceName: {{ include "esgf.component.fullname" (list . "search") }}
              servicePort: 8080
          {{- end }}
          {{- end }}
