{{- $fileServer := .Values.data.fileServer -}}
{{- if (and .Values.data.enabled $fileServer.enabled) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "esgf.component.fullname" (list . "fileServer") }}
  labels: {{ include "esgf.component.labels" (list . "fileServer" $fileServer.labels) | nindent 4 }}
data:
  datasets.conf: {{ tpl (.Files.Get "files/fileServer/datasets.conf") . | quote }}
{{ range $file, $content := $fileServer.extraNginxConf }}
  {{ $file }}: {{ tpl $content . | quote }}
{{- end }}
{{- end -}}
