{{- if .Values.index.enabled -}}
{{- $solr := .Values.index.solr -}}
{{- range $index, $replica := $solr.replicas -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "esgf.component.fullname" (list $ "solr" $replica.name) }}
  labels:
    {{ include "esgf.component.labels" (list $ "solr" $solr.labels) | indent 4 | trim }}
    solr.esgf.org/role: "replica"
    solr.esgf.org/replica-name: {{ $replica.name }}
spec:
  type: ClusterIP
  ports:
    - name: solr
      port: 8983
      targetPort: solr
      protocol: TCP
  selector:
    {{ include "esgf.component.selectorLabels" (list $ "solr") | indent 4 | trim }}
    solr.esgf.org/role: "replica"
    solr.esgf.org/replica-name: {{ $replica.name }}
{{- end -}}
{{- end -}}
