{{- $solr := .Values.index.solr -}}
{{- if and .Values.index.enabled $solr.enabled $solr.persistence.enabled -}}
{{- range $index, $replica := $solr.replicas -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "esgf.component.fullname" (list $ "solr" $replica.name) }}
  labels:
    {{ include "esgf.component.labels" (list $ "solr" $solr.labels) | indent 4 | trim }}
    solr.esgf.org/role: "replica"
    solr.esgf.org/replica-name: {{ $replica.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $replica.persistentVolumeSize | default $solr.persistence.size.replica }}
  {{- if kindIs "string" $solr.persistence.storageClassName }}
  storageClassName: {{ $solr.persistence.storageClassName | quote }}
  {{- end }}
  {{- with $solr.persistence.selector }}
  selector: {{ toYaml . | nindent 10 }}
  {{- end }}
{{- end -}}
{{- end -}}
