{{- $solr := .Values.index.solr -}}
{{- if and .Values.index.enabled $solr.localEnabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "esgf.component.fullname" (list . "solr" "slave") }}
  labels:
    {{ include "esgf.component.labels" (list . "solr" $solr.labels) | indent 4 | trim }}
    solr.esgf.org/role: "slave"
spec:
  # Solr shards can currently only have one replica
  replicas: 1
  # To ensure there are no issues with two pods writing to the same cores, make sure old
  # pods are killed before new ones are started
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{ include "esgf.component.selectorLabels" (list . "solr") | indent 6 | trim }}
      solr.esgf.org/role: "slave"
  template:
    metadata:
      labels:
        {{ include "esgf.component.selectorLabels" (list . "solr") | indent 8 | trim }}
        solr.esgf.org/role: "slave"
    spec:
      {{- with (default $.Values.image.pullSecrets $solr.image.pullSecrets) }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $solr.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: solr
          {{ include "esgf.deployment.image" (list . $solr.image) }}
          args:
            - solr
            - -f
            - "-Dslave.enable=true"
            - "-Dslave.masterUrl=http://{{ include "esgf.component.fullname" (list . "solr" "master") }}:8983/solr"
            - "-Dslave.pollInterval={{ $solr.slavePollInterval }}"
            # This is the Solr instance used for queries, so we need to enable shards
            # However we want to use a whitelist so that only queries for local shards are allowed
            - "-Dsolr.shardsWhitelist={{ include "esgf.solr.shardsWhitelist" . }}"
          # Merge the slave-specific resources with the Solr ones
          resources: {{ mergeOverwrite $solr.resources $solr.slaveResources | toYaml | nindent 12 }}
          ports:
            - name: solr
              containerPort: 8983
          readinessProbe: &probe
            httpGet:
              path: /solr/
              port: 8983
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            <<: *probe
            initialDelaySeconds: 60
          {{- with $solr.securityContext }}
          securityContext: {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            # In order to allow the filesystem to be read-only, mount ephemeral volumes
            # in places where writes are expected
            - name: tmp
              mountPath: /tmp
            - name: solr-logs
              mountPath: /var/solr/logs
            - name: solr-home
              mountPath: /var/solr/data
      {{- with $solr.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $solr.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $solr.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        # In order to allow the filesystem to be read-only, mount ephemeral volumes
        # in places where writes are expected
        - name: tmp
          emptyDir: {}
        - name: solr-logs
          emptyDir: {}
        - name: solr-home
          emptyDir: {}
{{- end -}}
