apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "fullname" . }}-hostcert"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: configuration
data:
  hostcert.crt: "{{ index .Values.certificates "hostcert.crt" | b64enc }}"
  hostcert.key: "{{ index .Values.certificates "hostcert.key" | b64enc }}"
