apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "fullname" . }}-slcs-ca"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: slcs
data:
  ca.crt: "{{ index .Values.certificates "slcsca.crt" | b64enc }}"
  ca.key: "{{ index .Values.certificates "slcsca.key" | b64enc }}"
