apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "fullname" . }}-trust-bundle"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: configuration
data:
  esg-trust-bundle.pem: |-
{{ index .Values.certificates "esg-trust-bundle.pem" | indent 4 }}
