apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "fullname" . }}-cog"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: cog
    cog-role: frontend
spec:
  replicas: {{ .Values.cog.replicas }}
  # Select pods on release and component only, rather than all labels
  # This means that the selector will match all pods from all versions of the chart when upgrading
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      component: cog
      cog-role: frontend
  template:
    metadata:
      labels:
{{ include "default-labels" . | indent 8 }}
        component: cog
        cog-role: frontend
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/configuration/secrets.yaml") . | sha256sum }}
        checksum/trust-bundle: {{ include (print $.Template.BasePath "/configuration/trust-bundle.yaml") . | sha256sum }}
    spec:
      initContainers:
        # Wait for databases to become available before starting
        - name: ensure-postgres-security
          image: "{{ .Values.cog.postgres.image.repository }}:{{ .Values.cog.postgres.image.tag }}"
          imagePullPolicy: {{ default "" .Values.cog.postgres.image.pullPolicy | quote }}
          env:
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: "{{ template "fullname" . }}-environment-common"
                  key: ESGF_DATABASE_HOST
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: "{{ template "fullname" . }}-environment-common"
                  key: ESGF_DATABASE_PORT
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: "{{ template "fullname" . }}-environment-common"
                  key: ESGF_DATABASE_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ template "fullname" . }}-secrets"
                  key: "security-database-password"
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: "{{ template "fullname" . }}-environment-common"
                  key: ESGF_DATABASE_NAME
          command:
            # Try every 5 seconds for no longer than 10 mins
            - bash
            - -c
            - |
              for i in $(seq 120); do
                sleep 5
                echo "Attempt $i of 120"
                if pg_isready; then exit 0; fi
              done
              exit 1
        - name: ensure-postgres-cog
          image: "{{ .Values.cog.postgres.image.repository }}:{{ .Values.cog.postgres.image.tag }}"
          imagePullPolicy: {{ default "" .Values.cog.postgres.image.pullPolicy | quote }}
          env:
            - name: PGHOST
              value: "{{ template "fullname" . }}-postgres-cog"
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: dbsuper
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ template "fullname" . }}-secrets"
                  key: "cog-database-password"
            - name: PGDATABASE
              value: cogdb
          command:
            # Try every 5 seconds for no longer than 10 mins
            - bash
            - -c
            - |
              for i in $(seq 120); do
                sleep 5
                echo "Attempt $i of 120"
                if pg_isready; then exit 0; fi
              done
              exit 1
      containers:
        - name: cog
          image: "{{ .Values.cog.image.repository }}:{{ .Values.cog.image.tag }}"
          imagePullPolicy: {{ default "" .Values.cog.image.pullPolicy | quote }}
          ports:
            - name: http
              containerPort: 8000
          # The readiness and liveness probes run the same thing, but the liveness
          # probe just waits a while before kicking in whereas the readiness probe
          # starts straight away
          readinessProbe: &probe
            httpGet:
              path: /
              port: 8000
              # The ALLOWED_HOSTS setting means that the app will only accept
              # requests from the correct host
              httpHeaders:
                - name: Host
                  value: "{{ .Values.hostname }}"
                - name: X-Forwarded-Host
                  value: "{{ .Values.hostname }}"
                - name: X-Forwarded-Proto
                  value: https
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            <<: *probe
            initialDelaySeconds: 600
          envFrom:
            - configMapRef:
                name: "{{ template "fullname" . }}-environment-common"
          env:
            - name: ESGF_COG_SITE_NAME
              value: "Local CoG"
            - name: ESGF_COG_HOME_PROJECT
              value: TestProject
            - name: ESGF_COG_TIME_ZONE
              value: "Europe/London"
            - name: ESGF_COG_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ template "fullname" . }}-secrets"
                  key: "cog-secret-key"
            - name: ESGF_COG_DATABASE_HOST
              value: "{{ template "fullname" . }}-postgres-cog"
            - name: ESGF_COG_DATABASE_PORT
              value: "5432"
            - name: ESGF_COG_DATABASE_NAME
              value: cogdb
            - name: ESGF_COG_DATABASE_USER
              value: dbsuper
            - name: ESGF_COG_DATABASE_PASSWORD_FILE
              value: /esg/secrets/cog-database-password
          volumeMounts:
            - mountPath: /esg/certificates/esg-trust-bundle.pem
              name: trust-bundle
              subPath: esg-trust-bundle.pem
            - mountPath: /esg/config/.esg_pg_pass
              name: esg-secrets
              subPath: security-database-password
            - mountPath: /esg/secrets/cog-database-password
              name: esg-secrets
              subPath: cog-database-password
            - mountPath: /esg/config/.esgf_pass
              name: esg-secrets
              subPath: rootadmin-password
          resources:
{{ toYaml .Values.cog.resources | indent 12 }}
      volumes:
        - name: trust-bundle
          configMap:
            name: "{{ template "fullname" . }}-trust-bundle"
        - name: esg-secrets
          secret:
            secretName: "{{ template "fullname" . }}-secrets"
