{{- if .Values.cog.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ template "fullname" . }}-postgres-cog"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: cog
    cog-role: database
spec:
  accessModes:
    - ReadWriteOnce
{{- if .Values.cog.postgres.persistence.storageClass }}
  storageClassName: "{{ .Values.cog.postgres.persistence.storageClass }}"
{{- end }}
  resources:
    requests:
      storage: {{ .Values.cog.postgres.persistence.size }}
{{- if .Values.cog.postgres.persistence.selector }}
  selector:
{{ toYaml .Values.cog.postgres.persistence.selector | indent 4 }}
{{- end }}
{{- end }}
