apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-cog"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: cog
    cog-role: frontend
spec:
  ports:
    - name: http
      port: 8000
  selector:
    release: {{ .Release.Name }}
    component: cog
    cog-role: frontend
