---

- name: Stop opa container
  docker_container:
    name: opa
    state: absent

- name: Stop auth service container
  docker_container:
    name: auth
    state: absent

- name: Remove auth config directory
  file:
    path: /esg/config/auth
    state: absent
