apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "esgf.component.fullname" (list . "config") }}
  labels: {{ include "esgf.component.labels" (list . "config") | nindent 4 }}
data:
{{ tpl (.Files.Glob "files/config/*").AsConfig . | indent 2 }}
