apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "fullname" . }}-orp"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: orp
spec:
  replicas: {{ .Values.orp.replicas }}
  # Select pods on release and component only, rather than all labels
  # This means that the selector will match all pods from all versions of the chart when upgrading
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      component: orp
  template:
    metadata:
      labels:
{{ include "default-labels" . | indent 8 }}
        component: orp
      annotations:
        checksum/hostcert: {{ include (print $.Template.BasePath "/configuration/hostcert.yaml") . | sha256sum }}
        checksum/trust-bundle: {{ include (print $.Template.BasePath "/configuration/trust-bundle.yaml") . | sha256sum }}
        checksum/environment-common: {{ include (print $.Template.BasePath "/configuration/environment-common.yaml") . | sha256sum }}
        checksum/esg-config-overrides: {{ include (print $.Template.BasePath "/configuration/esg-config-overrides.yaml") . | sha256sum }}
    spec:
      containers:
        - name: orp
          image: "{{ .Values.orp.image.repository }}:{{ .Values.orp.image.tag }}"
          imagePullPolicy: {{ default "" .Values.orp.image.pullPolicy | quote }}
          ports:
            - name: http
              containerPort: 8080
          # The readiness and liveness probes run the same thing, but the liveness
          # probe just waits a while before kicking in whereas the readiness probe
          # starts straight away
          readinessProbe: &probe
            httpGet:
              path: /esg-orp/home.htm
              port: 8080
              # This endpoint requires HTTPS, so simulate it
              httpHeaders:
                - name: Host
                  value: "{{ .Values.hostname }}"
                - name: X-Forwarded-Proto
                  value: https
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            <<: *probe
            initialDelaySeconds: 600
          envFrom:
            - configMapRef:
                name: "{{ template "fullname" . }}-environment-common"
          env:
            - name: ESGF_KEYSTORE_ALIAS
              value: "{{ .Values.hostname }}"
            - name: ESGF_SAML_CERT_FILE
              value: /esg/certificates/hostcert/hostcert.crt
            - name: ESGF_SAML_KEY_FILE
              value: /esg/certificates/hostcert/hostcert.key
          volumeMounts:
            - mountPath: /esg/certificates/hostcert
              name: hostcert
              readOnly: true
            - mountPath: /esg/certificates/esg-trust-bundle.pem
              name: trust-bundle
              subPath: esg-trust-bundle.pem
              readOnly: true
            - mountPath: /esg/config/.overrides
              name: esg-config-overrides
              readOnly: true
          resources:
{{ toYaml .Values.orp.resources | indent 12 }}
      volumes:
        - name: hostcert
          secret:
            secretName: "{{ template "fullname" . }}-hostcert"
        - name: trust-bundle
          configMap:
            name: "{{ template "fullname" . }}-trust-bundle"
        - name: esg-config-overrides
          configMap:
            name: "{{ template "fullname" . }}-esg-config-overrides"
