apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-orp"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: orp
spec:
  ports:
    - name: http
      port: 8080
  selector:
    release: {{ .Release.Name }}
    component: orp
