#!/bin/bash

set -eo pipefail

echo "****************************"
echo "** esgf-docker setup tool **"
echo "****************************"
echo ""
echo "The following commands are available:"
echo ""
echo "    generate-test-certificates"
echo "        Generates self-signed certificates for a test installation"
echo ""
echo "    generate-secrets"
echo "        Generates random secret keys and password required for deployment"
echo ""
echo "    create-trust-bundle"
echo "        Creates a PEM-encoded trust bundle from the available certificates"
echo ""
echo "    create-helm-configs"
echo "        Creates YAML files containing secrets and certificates for use with Helm"
echo ""
