#!/bin/bash

set -eo pipefail

source "$(dirname "$(realpath "$0")")/functions.sh"

#####
## This script creates a PEM-encoded trust bundle containing the following certificates:
##
##   1. Certificates from $ESGF_CONFIG/certificates/esg_trusted_certificates.tar, if present
##   2. The SLCS CA certificate, only if it is self-signed
##   3. The host SSL certificate, only if it is self-signed
#####

[ -z "$ESGF_HOSTNAME" ] && error "ESGF_HOSTNAME must be set"

CERTS="/esg/certificates"

info "Creating PEM-encoded trust bundle"

BUNDLE="$CERTS/esg-trust-bundle.pem"
rm -f "$BUNDLE"
touch "$BUNDLE"

# If the tarball exists, unpack it and add the certificates to the bundle
if [ -f "$CERTS/esg_trusted_certificates.tar" ]; then
    info "Unpacking existing trustroots"
    tar -xf "$CERTS/esg_trusted_certificates.tar" -C "$CERTS"
    for certfile in $(grep -lr -- "-----BEGIN CERTIFICATE-----" "$CERTS/esg_trusted_certificates"); do
        info "  Appending $certfile to bundle"
        cat "$certfile" >> "$BUNDLE"
    done
    rm -rf "$CERTS/esg_trusted_certificates"
else
    warn "esg_trusted_certificates.tar not present"
fi

# If the SLCS CA certificate is self-signed, add it to the trust bundle
if [ -f "$CERTS/slcsca/ca.crt" ]; then
    # To test if the certificate is self-signed, we ask openssl to verify the
    # certificate with the same file as the CA file
    # If this is successful then the certificate is self-signed
    if openssl verify -CAfile "$CERTS/slcsca/ca.crt" "$CERTS/slcsca/ca.crt" > /dev/null 2>&1; then
        info "Appending self-signed SLCS CA to trust bundle"
        cat "$CERTS/slcsca/ca.crt" >> "$BUNDLE"
    else
        warn "SLCS CA is not self-signed - skipping"
    fi
else
    warn "SLCS CA does not exist - skipping"
fi

# If the host SSL certificate is self-signed, add it to the trust bundle
if [ -f "$CERTS/hostcert/hostcert.crt" ]; then
    if openssl verify -CAfile "$CERTS/hostcert/hostcert.crt" "$CERTS/hostcert/hostcert.crt" > /dev/null 2>&1; then
        info "Appending self-signed host certificate to trust bundle"
        cat "$CERTS/hostcert/hostcert.crt" >> "$BUNDLE"
    else
        warn "Host certificate is not self-signed - skipping"
    fi
else
    warn "Host certificate does not exist - skipping"
fi

info "Done"
