#!/bin/bash

set -eo pipefail

source "$(dirname "$(realpath "$0")")/functions.sh"

#####
## This script generates random secrets for the various passwords and secret keys
## that are required for an ESGF deployment.
#####

SECRETS="/esg/secrets"
mkdir -p "$SECRETS"

info "Generating required secrets"

function try_create_secret {
    # First argument is secret name
    # Second argument is length, with default of 20
    [ -z "$1" ] && error "try_create_secret: Secret name must be given"
    if [ -f "$SECRETS/$1" ]; then
        warn "Secret '$1' already exists"
    else
        echo -n "$(tr -dc '[:alnum:]' < /dev/urandom | head -c "${2:-20}")" > "$SECRETS/$1"
        info "Created new secret '$1'"
    fi
}

# Passwords
#   This is the Java trust bundle
try_create_secret "java-trust-bundle-password"
#   This Java bundle contains the host certificate and key for SAML signing
try_create_secret "java-hostcert-bundle-password"
try_create_secret "rootadmin-password"
try_create_secret "database-password"
try_create_secret "database-publisher-password"
try_create_secret "slcs-database-password"
try_create_secret "auth-database-password"
# Secret keys
try_create_secret "cog-secret-key" 100
try_create_secret "shared-cookie-secret-key" 100
try_create_secret "slcs-secret-key" 100
try_create_secret "auth-secret-key" 100

info "Done"
