#!/bin/bash

set -eo pipefail

. "$(dirname $BASH_SOURCE)/functions.sh"


#####
## This script generates test certificates for a local test installation. These
## certificates should obviously not be used in production.
##
## The following certificates are generated, unless they already exist:
##
##   1. A self-signed CA for the SLCS
##   2. A self-signed host certificate for SSL
#####

[ -z "$ESGF_HOSTNAME" ] && error "ESGF_HOSTNAME must be set"

CERTS="/esg/certificates"

info "Generating self-signed test certificates"

if [ ! -f "$CERTS/slcsca/ca.crt" ]; then
    : ${ESGF_SLCS_CA_SUBJECT:="/O=esgf/CN=$ESGF_HOSTNAME SLCS CA"}
    info "Creating self-signed CA for the SLCS with subject = $ESGF_SLCS_CA_SUBJECT"
    mkdir -p "$CERTS/slcsca"
    openssl req -new -nodes -x509 -extensions v3_ca -days 3650  \
        -subj "$ESGF_SLCS_CA_SUBJECT" \
        -keyout "$CERTS/slcsca/ca.key" \
        -out "$CERTS/slcsca/ca.crt"
else
    warn "SLCS CA already exists - skipping"
fi

if [ ! -f "$CERTS/hostcert/hostcert.crt" ]; then
    : ${ESGF_HOSTCERT_SUBJECT:="/O=esgf/CN=$ESGF_HOSTNAME"}
    info "Creating self-signed host certificate with subject = $ESGF_HOSTCERT_SUBJECT"
    mkdir -p "$CERTS/hostcert"
    openssl req -new -nodes -x509 -extensions v3_ca -days 3650  \
        -subj "$ESGF_HOSTCERT_SUBJECT" \
        -keyout "$CERTS/hostcert/hostcert.key" \
        -out "$CERTS/hostcert/hostcert.crt"
else
    warn "Host certificate already exists - skipping"
fi

info "Done"
