{{- if .Values.slcs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "esgf.component.fullname" (list . "slcs") }}
  labels: {{ include "esgf.component.labels" (list . "slcs") | nindent 4 }}
type: Opaque
data:
  # Inject the runtime settings ahead of the app settings, which are 10-
  05-runtime-settings.yaml: {{ tpl (.Files.Get "files/slcs/runtime-settings.yaml") . | b64enc | quote }}
{{- end }}
