apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "fullname" . }}-index-node"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: index-node
spec:
  replicas: {{ .Values.indexNode.replicas }}
  # Select pods on release and component only, rather than all labels
  # This means that the selector will match all pods from all versions of the chart when upgrading
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      component: index-node
  template:
    metadata:
      labels:
{{ include "default-labels" . | indent 8 }}
        component: index-node
      annotations:
        checksum/trust-bundle: {{ include (print $.Template.BasePath "/configuration/trust-bundle.yaml") . | sha256sum }}
    spec:
      initContainers:
        # Make sure Solr is up before starting
        - name: ensure-solr-slave
          image: "{{ .Values.solr.image.repository }}:{{ .Values.solr.image.tag }}"
          imagePullPolicy: {{ default "" .Values.solr.image.pullPolicy | quote }}
          args:
            - "wait-for-solr.sh"
            - "--max-attempts"
            - "120"
            - "--solr-url"
            - "http://{{ template "fullname" . }}-solr-slave:8983"
      containers:
        - name: index-node
          image: "{{ .Values.indexNode.image.repository }}:{{ .Values.indexNode.image.tag }}"
          imagePullPolicy: {{ default "" .Values.indexNode.image.pullPolicy | quote }}
          ports:
            - name: http
              containerPort: 8080
          # The readiness and liveness probes run the same thing, but the liveness
          # probe just waits a while before kicking in whereas the readiness probe
          # starts straight away
          readinessProbe: &probe
            httpGet:
              path: /esg-search/search
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            <<: *probe
            initialDelaySeconds: 600
          envFrom:
            - configMapRef:
                name: "{{ template "fullname" . }}-environment-common"
          env:
            - name: ESGF_SOLR_SHARDS
              value: "{{ template "fullname" . }}-solr-slave:8983/solr"
          volumeMounts:
            - mountPath: /esg/certificates/esg-trust-bundle.pem
              name: trust-bundle
              subPath: esg-trust-bundle.pem
          resources:
{{ toYaml .Values.indexNode.resources | indent 12 }}
      volumes:
        - name: trust-bundle
          configMap:
            name: "{{ template "fullname" . }}-trust-bundle"
