apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "fullname" . }}-proxy"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: proxy
spec:
  replicas: {{ .Values.proxy.replicas }}
  # Select pods on release and component only, rather than all labels
  # This means that the selector will match all pods from all versions of the chart when upgrading
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      component: proxy
  template:
    metadata:
      labels:
{{ include "default-labels" . | indent 8 }}
        component: proxy
      annotations:
        checksum/hostcert: {{ include (print $.Template.BasePath "/configuration/hostcert.yaml") . | sha256sum }}
        checksum/trust-bundle: {{ include (print $.Template.BasePath "/configuration/trust-bundle.yaml") . | sha256sum }}
    spec:
      containers:
        - name: proxy
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
          imagePullPolicy: {{ default "" .Values.proxy.image.pullPolicy | quote }}
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          env:
            - name: ESGF_HOSTNAME
              value: "{{ .Values.hostname }}"
            - name: ESGF_SOLR_UPSTREAM
              value: "http://{{ template "fullname" . }}-solr-slave.{{ .Release.Namespace }}.svc.cluster.local:8983"
            - name: ESGF_INDEX_NODE_UPSTREAM
              value: "http://{{ template "fullname" . }}-index-node.{{ .Release.Namespace }}.svc.cluster.local:8080"
            - name: ESGF_TDS_UPSTREAM
              value: "http://{{ template "fullname" . }}-tds.{{ .Release.Namespace }}.svc.cluster.local:8080"
            - name: ESGF_COG_UPSTREAM
              value: "http://{{ template "fullname" . }}-cog.{{ .Release.Namespace }}.svc.cluster.local:8000"
            - name: ESGF_ORP_UPSTREAM
              value: "http://{{ template "fullname" . }}-orp.{{ .Release.Namespace }}.svc.cluster.local:8080"
            - name: ESGF_IDP_UPSTREAM
              value: "http://{{ template "fullname" . }}-idp-node.{{ .Release.Namespace }}.svc.cluster.local:8080"
            - name: ESGF_SLCS_UPSTREAM
              value: "http://{{ template "fullname" . }}-slcs.{{ .Release.Namespace }}.svc.cluster.local:8000"
            - name: ESGF_AUTH_UPSTREAM
              value: "http://{{ template "fullname" . }}-auth.{{ .Release.Namespace }}.svc.cluster.local:8000"
          volumeMounts:
            - mountPath: /etc/nginx/ssl
              name: hostcert
            - mountPath: /esg/certificates/esg-trust-bundle.pem
              name: trust-bundle
              subPath: esg-trust-bundle.pem
          resources:
{{ toYaml .Values.proxy.resources | indent 12 }}
      volumes:
        - name: hostcert
          secret:
            secretName: "{{ template "fullname" . }}-hostcert"
        - name: trust-bundle
          configMap:
            name: "{{ template "fullname" . }}-trust-bundle"
