{{- if (and .Values.proxy.ingress.enabled (eq .Values.proxy.ingress.mode "openshift")) }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{ template "fullname" . }}-proxy"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: proxy
spec:
  host: "{{ .Values.hostname }}"
  to:
    kind: Service
    name: "{{ template "fullname" . }}-proxy"
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
{{- end }}
