apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-proxy"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: proxy
spec:
  ports:
    - name: https
      port: 443
  selector:
    release: {{ .Release.Name }}
    component: proxy
