{{- if eq .Values.database.type "internal" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "esgf.component.fullname" (list . "database") }}
  labels: {{ include "esgf.component.labels" (list . "database") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
  selector: {{ include "esgf.component.selectorLabels" (list . "database") | nindent 4 }}
{{- end -}}
