#!/bin/bash

set -euxo pipefail;

# Look for scripts in /docker-init.d and execute them in lexicograhpic order
if [ -d "/docker-init.d" ]; then
    for file in $(find /docker-init.d/ -mindepth 1 -type f -executable | sort -n); do
        case "$file" in
            *.sh) . $file ;;
            *) eval $file ;;
        esac
    done
fi

# Then start the given process
exec "$@"
