# Runtime settings for the SLCS

HOSTNAME: {{ .Values.hostname | quote }}
DATABASES:
  # Use the same database configuration for both databases
  default: &db
    ENGINE: django.db.backends.postgresql
    HOST: {{ include "esgf.database.host" . | quote }}
    PORT: {{ include "esgf.database.port" . | quote }}
    USER: {{ include "esgf.database.user" . | quote }}
    PASSWORD: {{ include "esgf.database.password" . | quote }}
    NAME: {{ include "esgf.database.dbname" . | quote }}
  userdb: *db
