{{- if (and .Values.proxy.ingress.enabled (eq .Values.proxy.ingress.mode "kubernetes")) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "fullname" . }}-visus"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: visus
  annotations:
    # This ingress is specifically for the Nginx ingress controller
    # It will be ignored by all other ingress controllers, and so can co-exist
    # with similar ingresses for other controllers
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
    - host: "{{ .Values.hostname }}"
      http:
        paths:
          - path: /esgf-visus/
            backend:
              serviceName: "{{ template "fullname" . }}-visus"
              servicePort: 8000
          - path: /esgf-visus
            backend:
              serviceName: "{{ template "fullname" . }}-visus"
              servicePort: 8000
  tls:
    - hosts:
      - "{{ .Values.hostname }}"
{{- end }}
