apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-visus"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: visus
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 80
  selector:
    release: {{ .Release.Name }}
    component: visus
