#!/bin/bash

set -eo pipefail

. /esg/bin/functions.sh

#####
## This script fetches a certificate from the SLCS for the given username and password
#####

info "Fetching short-lived certificate from $ESGF_SLCS_CERTIFICATE_URL"

username="$1"
[ -z "$username" ] && read -p "Username: " username
password="$2"
[ -z "$password" ] && read -s -p "Password: " password
echo

CERTFILE="/esg/config/esgcet/.globus/certificate-file"
mkdir -p /esg/config/esgcet/.globus/certificates

info "  Generating private key and CSR"
KEYFILE="$(mktemp)"
CSRFILE="$(mktemp)"
openssl req -new -nodes -batch -sha256 -newkey rsa:2048 -keyout "$KEYFILE" -out "$CSRFILE" >/dev/null 2>&1

info "  Fetching certificate"
curl -fsS -X POST \
    --user "$username:$password" \
    --data-urlencode "certificate_request@$CSRFILE" \
    "$ESGF_SLCS_CERTIFICATE_URL" > "$CERTFILE"
cat "$KEYFILE" >> "$CERTFILE"
rm "$KEYFILE" "$CSRFILE"

info "Complete"
