hostname: 192.168.99.101.nip.io

image:
  prefix: breezy.badc.rl.ac.uk:4567/github-mirrors/esgf__esgf-docker
  tag: 0322b008
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: breezy

persistence:
  enabled: false
  # Only used when database.type=internal and persistence.enabled=true
  database:
    # Set this to the name of a pre-existing persistentVolumeClaim
    existingClaim:
    # Set these to dynamically create a new persistentVolumeClaim
    # If no storage class is given, then the default is used
    storageClassName:
    size: 1Gi

ingress:
  enabled: true
  annotations:
  tlsSecretName:

database:
  type: internal
  external:
    host:
    port: 5432
    user:
    password:
    dbname:
  internal:
    # Specify a secure password in production
    password: changeme
    image:
      repository: postgres
    resources: {}

schemaMigrate:
  image:
    repository: schema-migrate
  resources: {}

idp:
  enabled: true
  image:
    repository: idp
  replicaCount: 1
  resources: {}

slcs:
  enabled: true
  image:
    repository: slcs
  replicaCount: 1
  resources: {}

myproxy:
  endpoint:
