hostname: esgf.130.246.129.72.nip.io

image:
  prefix: breezy.badc.rl.ac.uk:4567/github-mirrors/esgf__esgf-docker
  tag: 5d96ec18
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: breezy

persistence:
  enabled: false
  # Only used when database.type=internal and persistence.enabled=true
  database:
    # Set this to the name of a pre-existing persistentVolumeClaim
    existingClaim:
    # Set these to dynamically create a new persistentVolumeClaim
    # If no storage class is given, then the default is used
    storageClassName:
    size: 1Gi

ingress:
  enabled: true
  annotations:
  tlsSecretName: esgf-tls

database:
  type: internal
  external:
    host:
    port: 5432
    user:
    password:
    dbname:
  internal:
    # Specify a secure password in production
    password: changeme
    image:
      repository: postgres
    resources: {}

config:
  ats: []
    # - type: "CMIP5 Research"
    #   attributeService: "https://esgf-node.llnl.gov/esgf-idp/saml/soap/secure/attributeService.htm"
    #   description: "Users of CMIP5 data for non-commercial research purposes only"
    #   registrationService: "https://esgf-node.llnl.gov/esgf-idp/secure/registrationService.htm"
  cogs: []
    # - name: "CoG-CU"
    #   domain: "www.earthsystemcog.org"
  endpoints: []
    # - name: "jplnasagov#public"
    #   gridftp: "esgf-node.jpl.nasa.gov:2811"
    #   pathOut: "/esg_dataroot"
  idps: []
    # - https://esgf-node.llnl.gov/esgf-idp/idp/openidServer.htm
    # - https://ceda.ac.uk/OpenID/Provider/server
  knownProviders: []
    # - name: DOE Lawrence Livermore National Laboratory (LLNL)
    #   url: https://esgf-node.llnl.gov/esgf-idp/openid/
  searchAliases:
    # This is a list of lists, which comprise the sets
    - [project, model_cohort]
    - [project, model_cohort]
    - [activity, experiment_family]
  shards: []
    # - esgf-node.llnl.gov/solr
    # - esgf-index1.ceda.ac.uk/solr
  lasServers: []
    # - name: "ESGF-JPL-NODE"
    #   url: "http://esgf-node.jpl.nasa.gov/las"
    #   ip: "128.149.121.151"

schemaMigrate:
  image:
    repository: schema-migrate
  resources: {}

idp:
  enabled: true
  image:
    repository: idp
  replicaCount: 1
  resources: {}

slcs:
  enabled: true
  image:
    repository: slcs
  replicaCount: 1
  resources: {}

orp:
  enabled: true
  image:
    repository: orp
  replicaCount: 1
  resources: {}

myproxy:
  endpoint:
