hostname: esgf.130.246.129.72.nip.io

image:
  prefix: breezy.badc.rl.ac.uk:4567/github-mirrors/esgf__esgf-docker
  tag: "4f0af764"
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: breezy

persistence:
  enabled: false
  # Only used when database.type=internal and persistence.enabled=true
  database:
    # Set this to the name of a pre-existing persistentVolumeClaim
    existingClaim:
    # Set these to dynamically create a new persistentVolumeClaim
    # If no storage class is given, then the default is used
    storageClassName:
    size: 1Gi

ingress:
  annotations:
  tls:
    # Either give an existing secret name
    secretName:
    # Or provide PEM-encoded certificate (including chain) and key files
    pem:
      cert:
      key:

thredds:
  enabled: true
  image:
    repository: thredds
  replicaCount: 1
  resources: {}
