apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: esgf-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: my-node.esgf.org
    http:
      paths:
      - path: /
        backend:
          serviceName: esgf-tds
          servicePort: 8080
