apiVersion: v1
kind: Service
metadata:
  name: esgf-tds
  labels:
    stack: esgf
    app: tds
spec:
  type: NodePort
  ports:
  - port: 8080 # host port
    targetPort: 8080 # container port
    protocol: TCP
    name: tomcat-http
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: tomcat-https
  # the selector identifies the set of pods to load-balance against
  selector:
    stack: esgf
    app: tds
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: esgf-tds
spec:
  replicas: 1
  template:
    metadata:
      labels:
        stack: esgf
        app: tds
    spec:
      containers:
      - name: esgf-tds
        image: esgfhub/esgf-tds:devel
        ports:
        - containerPort: 8080
        - containerPort: 8443
        volumeMounts:
        - name: tds-data
          mountPath: /esg/content/thredds
        - name: esgf-config-archive
          mountPath: /root/archives/esgf_config.tar.xz
        readinessProbe:
          httpGet:
            path: /thredds
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: tds-data
        emptyDir: {}
      - name: esgf-config-archive
        hostPath:
          path: /Users/cinquini/ESGF_CONFIG/archives/esgf_config.tar.xz
