apiVersion: v1
kind: Service
metadata:
  name: esgf-tds
  labels:
    stack: esgf
    app: tds
spec:
  type: NodePort
  ports:
  - port: 8080 # host port
    targetPort: 8080 # container port
    protocol: TCP
    name: tomcat-http
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: tomcat-https
  - port: 8009
    targetPort: 8009
    protocol: TCP
    name: tomcat-ajp
  # the selector identifies the set of pods to load-balance against
  selector:
    stack: esgf
    app: tds
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tds-data-pvc
  labels:
    stack: esgf
    app: tds
spec:
  selector:
    matchLabels:
      app: tds
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esg-data-pvc
  labels:
    stack: esgf
    app: climate-data
spec:
  selector:
    matchLabels:
      app: climate-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: esgf-tds
spec:
  replicas: 1
  template:
    metadata:
      labels:
        stack: esgf
        app: tds
    spec:
      initContainers:
      # container used to delay this pod's initialization untill postgres database is available
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nslookup esgf-postgres; do echo waiting for esgf-postgres; sleep 1; done;']
      containers:
      - name: esgf-tds
        image: esgfhub/esgf-tds:devel
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: esgf-env
        volumeMounts:
        - name: tds-data
          mountPath: /esg/content/thredds
        - name: esg-data
          mountPath: /esg/data
        - name: esgf-config-archive
          mountPath: /root/archives/esgf_config.tar.xz
        - name: tds-web-xml
          mountPath: /usr/local/tomcat/webapps/thredds/WEB-INF/web.xml
        - name: tomcat-esg-truststore
          mountPath: /usr/java/latest/jre/lib/security/jssecacerts
        #readinessProbe:
        #  httpGet:
        #    path: /thredds
        #    port: 8080
        #  initialDelaySeconds: 5
        #  periodSeconds: 10
      # publisher container must be co-located with tds container
      # to be able to write thredds catalogs to /esg/content/tredds
      - name: esgf-publisher
        image: esgfhub/esgf-publisher:devel
        volumeMounts:
        - name: tds-data
          mountPath: /esg/content/thredds
        - name: esg-data
          mountPath: /esg/data
        - name: esgf-config-archive
          mountPath: /root/archives/esgf_config.tar.xz
        envFrom:
        - configMapRef:
            name: esgf-env
        env:
        - name: SSL_CERT_DIR
          value: /etc/grid-security/certificates

      volumes:
      #- name: tds-data
      #  emptyDir: {}
      #- name: esg-data
      #  emptyDir: {}
      - name: esgf-config-archive
        hostPath:
          path: /Users/cinquini/ESGF_CONFIG/archives/esgf_config.tar.xz
      - name: tds-web-xml
        hostPath:
          path: /Users/cinquini/ESGF_CONFIG/webapps/thredds/WEB-INF/web.xml
      - name: tomcat-esg-truststore
        hostPath:
          path: /Users/cinquini/ESGF_CONFIG/esg/config/tomcat/esg-truststore.ts
      - name: tds-data
        persistentVolumeClaim:
          claimName: tds-data-pvc
      - name: esg-data
        persistentVolumeClaim:
          claimName: esg-data-pvc
