{{- $opa := .Values.opa -}}
{{- if ($opa.enabled) -}}
apiVersion: v1
data:
  policy.rego: |-
    package esgf

    default allow = false

    allow {
        re_match("^/thredds/(fileServer|dodsC)/cmip5..*.aggregation.*", input.resource)
        input.action = "Read"
    }

    allow {
        regex.match("^/thredds/catalog/esgcet/c3s-cordex/.*", input.resource)
        input.subject.groups[_] = "/cordex_research/publish"
        input.action = "Write"
    }
kind: ConfigMap
metadata:
  name: {{ include "esgf.component.fullname" (list . "policy") }}
  labels: {{ include "esgf.component.labels" (list . "policy" $opa.labels) | nindent 4 }}
{{- end -}}
