{{- $opa := .Values.opa -}}
{{- if ($opa.enabled) -}}
apiVersion: v1
data:
  example.rego: |-
    package example

    greeting = msg {
        info := opa.runtime()
        hostname := info.env["HOSTNAME"] # Kubernetes sets the HOSTNAME environment variable.
        msg := sprintf("hello from pod %q!", [hostname])
    }
kind: ConfigMap
metadata:
  name: {{ include "esgf.component.fullname" (list . "policy") }}
  labels: {{ include "esgf.component.labels" (list . "policy" $opa.labels) | nindent 4 }}
{{- end -}}
