{{- if .Values.data.thredds.enabled -}}
{{- $thredds := .Values.data.thredds -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "esgf.component.fullname" (list . "thredds") }}
  labels: {{ include "esgf.component.labels" (list . "thredds") | nindent 4 }}
spec:
  replicas: {{ $thredds.replicaCount }}
  selector:
    matchLabels: {{ include "esgf.component.selectorLabels" (list . "thredds") | nindent 6 }}
  template:
    metadata:
      labels: {{ include "esgf.component.selectorLabels" (list . "thredds") | nindent 8 }}
      # Force deployment to roll if the config changes
      # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/thredds/configmap.yaml") . | sha256sum }}
    spec:
      {{- with (default .Values.image.pullSecrets $thredds.image.pullSecrets) }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.data.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: thredds
          {{ include "esgf.deployment.image" (list . $thredds) }}
          resources: {{ toYaml $thredds.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
          readinessProbe: &probe
            httpGet:
              path: /thredds/
              port: 8080
              httpHeaders:
                - name: Host
                  value: "{{ .Values.hostname }}"
                - name: X-Forwarded-Host
                  value: "{{ .Values.hostname }}"
                - name: X-Forwarded-Proto
                  value: https
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            <<: *probe
            initialDelaySeconds: {{ .Values.data.thredds.startTimeout }}
          {{- with .Values.data.securityContext }}
          securityContext: {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: catalog-esgcet
              mountPath: /opt/tomcat/content/thredds/esgcet
              readOnly: true
              {{- with (omit .Values.data.catalogVolume "volume") }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- include "esgf.data.volumeMounts" . | nindent 12 }}
      {{- with $thredds.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $thredds.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $thredds.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: catalog-esgcet
          {{- if .Values.data.catalogVolume.volume }}
          {{- toYaml .Values.data.catalogVolume.volume | nindent 10 }}
          {{- else }}
          configMap:
            name: {{ include "esgf.component.fullname" (list . "thredds") }}
          {{- end }}
        {{- include "esgf.data.volumes" . | nindent 8 }}
{{- end -}}
