{{- $wgetApi := .Values.index.wgetApi -}}
{{- if (and .Values.index.enabled $wgetApi.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: wget-api-secret
type: Opaque
data:
  secret: {{ randAlphaNum 50 | b64enc }}
{{- end -}}
