{{- $wgetApi := .Values.index.wgetApi -}}
{{- if (and .Values.index.enabled $wgetApi.enabled) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "esgf.component.fullname" (list . "wgetApi") }}
  labels: {{ include "esgf.component.labels" (list . "wgetApi" $wgetApi.labels) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8000
      protocol: TCP
  selector: {{ include "esgf.component.selectorLabels" (list . "wgetApi") | nindent 4 }}
{{- end -}}
