{{- $auth := .Values.auth -}}
{{- if ($auth.enabled) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "esgf.component.fullname" (list . "auth") }}
  labels: {{ include "esgf.component.labels" (list . "auth" $auth.labels) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector: {{ include "esgf.component.selectorLabels" (list . "auth") | nindent 4 }}
{{- end -}}
