title: ESGF Docker
description: Documentation for the ESGF Docker project.
url: "https://cedadev.github.io/esgf-docker"
baseurl:
show_full_navigation: true
author:
  name: Matt Pryor
  email: matt.pryor@stfc.ac.uk

permalink: pretty
collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
      toc: true
#  - scope:
#      path: ""
#      type: "docs"
#    values:
#      seo:
#        type: Article
#      _comments:
#        category: Group navigation links with this field
#        order: Used to sort links in the navigation
#      _options:
#        content:
#          width: 800
#          height: 2000

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
