---

#####
## Tasks to configure and deploy containers for an index node
#####

- name: Install Solr
  include: solr_install.yml
  when: "'index' in group_names and solr_enabled"

- name: Uninstall Solr
  include: solr_uninstall.yml
  when: "'index' not in group_names or not solr_enabled"

- name: Reconcile Solr replicas
  include: solr_replica_reconcile.yml

- name: Install search application
  include: search_install.yml
  when: "'index' in group_names and search_enabled"

- name: Uninstall search application
  include: search_uninstall.yml
  when: "'index' not in group_names or not search_enabled"

- name: Install wget_api application
  include: wget_api_install.yml
  when: "'index' in group_names and wget_api_enabled"

- name: Uninstall wget_api application
  include: wget_api_uninstall.yml
  when: "'index' not in group_names or not wget_api_enabled"
