---

- name: Add Docker Repo
  command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  register: docker_install

- name: Remove podman installation
  command: dnf remove -y podman buildah

- name: Install Docker
  command: dnf install -y docker-ce docker-ce-cli containerd.io

- name: Start Docker Daemon
  command: systemctl start docker

- name: Make docker.service.d directory
  file:
    path: /usr/lib/systemd/system/docker.service.d
    state: directory

# This is important for mount propagation
- name: Set Docker mount flags
  copy:
    dest: /usr/lib/systemd/system/docker.service.d/mount_flags.conf
    content: |
      [Service]
      MountFlags=shared
  register: mount_flags_updated

# Changing the systemd files requires a daemon reload
- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  when: mount_flags_updated is changed
  register: system_daemon_reload

- name: Restart Docker
  service:
    name: docker
    state: restarted
    enabled: yes
  # When the Docker installation changes, restart Docker
  when: docker_install is changed or system_daemon_reload is changed

# The Ansible Docker modules require the Docker Python SDK, which requires pip to install, which requires EPEL

- name: Install python-pip
  command: dnf install -y python-pip

- name: Install Docker SDK
  command: python3 -m pip install docker

## Log in to the configured registries
- name: Log in to Docker registry
  docker_login:
    registry: "{{ item.registry }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
  loop: "{{ docker_registries }}"
  loop_control:
    label: "{{ item.registry }}"
