name: Release

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]*"

permissions: {}

jobs:
  helm:
    name: Publish Helm chart
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.5.0
        with:
          name: esgf
          repository: ESGF/charts
          tag: ${{ github.ref_name }}
          path: deploy/kubernetes/chart
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: "true"
